/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HundredRouteImport } from './routes/hundred'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as ExerciseExerciseIdRouteImport } from './routes/exercise.$exerciseId'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HundredRoute = HundredRouteImport.update({
  id: '/hundred',
  path: '/hundred',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseExerciseIdRoute = ExerciseExerciseIdRouteImport.update({
  id: '/exercise/$exerciseId',
  path: '/exercise/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/hundred': typeof HundredRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/streak': typeof StreakRoute
  '/workout': typeof WorkoutRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/hundred': typeof HundredRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/streak': typeof StreakRoute
  '/workout': typeof WorkoutRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/hundred': typeof HundredRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/streak': typeof StreakRoute
  '/workout': typeof WorkoutRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/hundred'
    | '/settings'
    | '/stats'
    | '/streak'
    | '/workout'
    | '/exercise/$exerciseId'
    | '/join/$inviteCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/hundred'
    | '/settings'
    | '/stats'
    | '/streak'
    | '/workout'
    | '/exercise/$exerciseId'
    | '/join/$inviteCode'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/hundred'
    | '/settings'
    | '/stats'
    | '/streak'
    | '/workout'
    | '/exercise/$exerciseId'
    | '/join/$inviteCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HundredRoute: typeof HundredRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  StreakRoute: typeof StreakRoute
  WorkoutRoute: typeof WorkoutRoute
  ExerciseExerciseIdRoute: typeof ExerciseExerciseIdRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundred': {
      id: '/hundred'
      path: '/hundred'
      fullPath: '/hundred'
      preLoaderRoute: typeof HundredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/$exerciseId': {
      id: '/exercise/$exerciseId'
      path: '/exercise/$exerciseId'
      fullPath: '/exercise/$exerciseId'
      preLoaderRoute: typeof ExerciseExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HundredRoute: HundredRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  StreakRoute: StreakRoute,
  WorkoutRoute: WorkoutRoute,
  ExerciseExerciseIdRoute: ExerciseExerciseIdRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
