/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HundredRouteImport } from './routes/hundred'
import { Route as ExerciseExerciseIdRouteImport } from './routes/exercise.$exerciseId'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HundredRoute = HundredRouteImport.update({
  id: '/hundred',
  path: '/hundred',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseExerciseIdRoute = ExerciseExerciseIdRouteImport.update({
  id: '/exercise/$exerciseId',
  path: '/exercise/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/hundred': typeof HundredRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/hundred': typeof HundredRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/hundred': typeof HundredRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exercise/$exerciseId' | '/hundred' | '/settings' | '/stats' | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exercise/$exerciseId' | '/hundred' | '/settings' | '/stats' | '/workout'
  id: '__root__' | '/' | '/exercise/$exerciseId' | '/hundred' | '/settings' | '/stats' | '/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExerciseExerciseIdRoute: typeof ExerciseExerciseIdRoute
  HundredRoute: typeof HundredRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundred': {
      id: '/hundred'
      path: '/hundred'
      fullPath: '/hundred'
      preLoaderRoute: typeof HundredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/$exerciseId': {
      id: '/exercise/$exerciseId'
      path: '/exercise/$exerciseId'
      fullPath: '/exercise/$exerciseId'
      preLoaderRoute: typeof ExerciseExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExerciseExerciseIdRoute: ExerciseExerciseIdRoute,
  HundredRoute: HundredRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
